package testData

import (
	"bjssStoreGo/backend/utils"
)

func GetAccountTestData() []utils.Account {
	return []utils.Account{
		{
			Id: 1,
			ShippingDetails: utils.ShippingDetails{
				Email:    "pre-populated-test-account@example.com",
				Name:     "Pre-populated Test Account",
				Address:  "123 Pre-Populated St, Test Town, Example",
				Postcode: "PL7 1RF",
			},
			// Generated by running account-services' hashPassword('I am an insecure password')
			PasswordHash: "flN+ZCd1vfgwose87/0dA0suvPYnDnuNxYRzWAmouLFsR/LV34DSev7BF3jc5M8uUFvXI4idZUumQ5jo/FPmnA==:Zedgm/FUGr7aJQWC9260kw==",
		},
		{
			Id: 2,
			ShippingDetails: utils.ShippingDetails{
				Email:    "pre-populated-test-account2@example.com",
				Name:     "Pre-populated Test Account 2",
				Address:  "32 Pre-Populated St, Test Town, Example",
				Postcode: "PL7 1RF",
			},
			// Generated by running account-services' hashPassword('I am an insecure password')
			PasswordHash: "flN+ZCd1vfgwose87/0dA0suvPYnDnuNxYRzWAmouLFsR/LV34DSev7BF3jc5M8uUFvXI4idZUumQ5jo/FPmnA==:Zedgm/FUGr7aJQWC9260kw==",
		},
	}
}

func GetTestAccountCredentials(indexes ...int) struct {
	Email    string
	Password string
} {
	index := 0

	if indexes != nil {
		index = indexes[0]
	}

	testAccount := GetAccountTestData()[index]

	return struct {
		Email    string
		Password string
	}{
		Email:    testAccount.Email,
		Password: "I am an insecure password",
	}
}
