package testData

import (
	"bjssStoreGo/backend/utils"
	"strconv"
)

func GetAccountTestData() []utils.Account {
	return []utils.Account{
		{
			Id: 1,
			ShippingDetails: utils.ShippingDetails{
				Email:    "pre-populated-test-account@example.com",
				Name:     "Pre-populated Test Account",
				Address:  "123 Pre-Populated St, Test Town, Example",
				Postcode: "PL7 1RF",
			},
			// Generated by running account-services' hashPassword('I am an insecure password')
			PasswordHash: "flN+ZCd1vfgwose87/0dA0suvPYnDnuNxYRzWAmouLFsR/LV34DSev7BF3jc5M8uUFvXI4idZUumQ5jo/FPmnA==:Zedgm/FUGr7aJQWC9260kw==",
		},
		{
			Id: 2,
			ShippingDetails: utils.ShippingDetails{
				Email:    "pre-populated-test-account2@example.com",
				Name:     "Pre-populated Test Account 2",
				Address:  "32 Pre-Populated St, Test Town, Example",
				Postcode: "PL7 1RF",
			},
			// Generated by running account-services' hashPassword('I am an insecure password')
			PasswordHash: "flN+ZCd1vfgwose87/0dA0suvPYnDnuNxYRzWAmouLFsR/LV34DSev7BF3jc5M8uUFvXI4idZUumQ5jo/FPmnA==:Zedgm/FUGr7aJQWC9260kw==",
		},
	}
}

func GetTestAccountCredentials(ids ...int) struct {
	Email    string
	Password string
} {
	id := 1

	if ids != nil {
		id = ids[0]
	}

	testAccount := getTestAccountFromId(id)

	return struct {
		Email    string
		Password string
	}{
		Email:    testAccount.Email,
		Password: "I am an insecure password",
	}
}

func getTestAccountFromId(id int) utils.Account {
	allAccounts := GetAccountTestData()

	for _, account := range allAccounts {
		if account.Id == id {
			return account
		}
	}
	panic("Account with id " + strconv.Itoa(id) + " not found")
}
